#!/usr/bin/env bash
set -euo pipefail
# generate-matrix.sh
# Produces a JSON matrix with top-level changed folders (excludes .github and docs)

### ENV is generated by GitHub Actions env: block
## For pull_request triggers, the following are set
# DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
# BASE_SHA: ${{ github.event.pull_request.base.sha }}
# HEAD_SHA: ${{ github.event.pull_request.head.sha }}
# ACTION: ${{ github.event.action }}
## For push triggers (e.g., merge a PR to main), the following are set
# TBD

# exit script if not running in GHA
if [ -z "${GITHUB_SHA:-}" ]; then
  echo "GITHUB_SHA not set; are you running inside GitHub Actions?" >&2
  exit 1
fi

# Allow for a test diff for local testing
if [ -n "${TEST_DIFF:-}" ]; then
  DIFF="$TEST_DIFF"
else
  echo "--BASE_SHA--"
  echo "$BASE_SHA"
  echo ""
  echo "--HEAD_SHA--"
  echo "$HEAD_SHA"
  echo ""
  echo "--DEFAULT_BRANCH--"
  echo "$DEFAULT_BRANCH"
  echo ""
  echo "--ACTION--"
  echo "$ACTION"
  echo ""

  # Collect changed files/folders, filter out .github and docs
  DIFF=$( git diff --dirstat=files,0,cumulative "$BASE_SHA" "$GITHUB_SHA" | awk -F ' ' '{print $2}' | grep -vE '(^.github)' || true )
  echo "--DIFF--"
  echo "$DIFF"
  echo ""
fi

# Extract top-level directories only (ignore files in repo root) and dedupe
TOP_LEVEL=$( printf "%s\n" "$DIFF" | grep '/' | awk -F/ '{print $1}' | grep -vE '^(\\.github)$' | sort -u || true )
echo "--TOP_LEVEL--"
echo "$TOP_LEVEL"
echo ""

# Build JSON
JSON='{"paths":['
first=true
while IFS= read -r p; do
  [ -z "$p" ] && continue
  if [ "$first" = true ]; then
    JSON="$JSON\"$p\""
    first=false
  else
    JSON="$JSON,\"$p\""
  fi
done <<< "$TOP_LEVEL"
JSON="$JSON]}"

# Export matrix via GITHUB_OUTPUT if available (GitHub Actions); otherwise skip
if [ -n "${GITHUB_OUTPUT:-}" ]; then
  echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
  echo "$JSON" >> "$GITHUB_OUTPUT"
  echo "EOF" >> "$GITHUB_OUTPUT"
fi

# Also print to logs for debugging
echo "$JSON"
